###
----------------------------------------------------------------------
 
           +---+---+---+---+
 chaos --> | J | B | U | S | --> order
           +---+---+---+---+

Copyright (C) 2015 Encapsule.io Bellevue, WA USA

JBUS is licensed under the GNU Affero General Public License v3.0. 
Please consult the included LICENSE file for agreement terms.

----------------------------------------------------------------------
###
#
#
#

module.exports =

    outputName: "FilterDAG Object"
    outputDescription: "A FilterDAG reactive systems host object generated by the FilterDAG factory."

    outputFilterSpec:
        ____label: "FilterDAG"
        ____description: "FilterDAG reactive system host object."
        ____types: "jsObject"

        'fdnFVPtSQy6UR79kQ_AdHA':
            ____label: "FilterDAG Object Watermark"
            ____description: "Unique IRUT assigned to all FilterDAG objects to facilitate runtime identification."
            ____accept: "jsBoolean"
            ____defaultValue: true


        dagID: ____opaque: true
        dagIID: ____opaque: true
        dagName: ____opaque: true
        dagDescription: ____opaque: true
        dagSpecification: ____opaque: true
